apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: 1.0.57
    helm:
      releaseName: portainer
      valueFiles:
        - https://raw.githubusercontent.com/portainer/k8s/master/charts/portainer/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: portainer

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
