apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd  # Argo CD's namespace
spec:
  project: default

  source:
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: 1.0.57  # use latest version or a specific one
    helm:
      releaseName: portainer
      values: |
        service:
          type: LoadBalancer
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
