apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: 1.0.57
    helm:
      releaseName: portainer
      values: |
        service:
          type: LoadBalancer

        persistence:
          enabled: false

        ingress:
          enabled: false
          className: ""
          annotations: {}
          hosts:
            - host: portainer.local
              paths:
                - path: /
                  pathType: Prefix
          tls: []

        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 250m

        nodeSelector: {}
        tolerations: []
        affinity: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: portainer